AWSTemplateFormatVersion: '2010-09-09'
Description: 'OIDC Identity Provider para GitHub Actions - Projeto Hermes'
Resources:
  GitHubOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
        - 6938fd4d98bab03faadb97b34396831e3780aea1
  GitHubActionsDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: GitHubActionsDeployRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GitHubOidcProvider
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub:
                  - repo:melkyfb/hermes-cloud-infra:ref:refs/heads/main
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
Outputs:
  RoleArn:
    Description: 'ARN da Role para os workflows do GitHub Actions'
    Value: !GetAtt GitHubActionsDeployRole.Arn
